app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => 'guest'], function(){
     	Route::get('/', function(){
			return redirect('/login');
		});
});

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
|
*/
Route::auth();
Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');



Route::post('/users/{id}/ctes', 'CTEsController@upload');
Route::post('/report/generate', 'ReportController@generate');

Route::group(['middleware' => ['auth']
    ], function () {
    	Route::get('/ctes/upload', 'CTEsController@uploader');
    	Route::get('/cte/{id}/wizard', 'CTEsController@EconomicActivitiesWizard');
 		Route::resource('cte', 'CTEsController');
 		Route::get('/cte/{id}/reports', 'ReportController@index'); 		
 		Route::get('/reports/{id}', 'ReportController@show');
 		Route::get('api/reports/{id}', 'api\ReportAPI@show');

    });

app/Models/Cte.php
<?php

namespace acempresarial\Models;

use Illuminate\Database\Eloquent\Model;
use acempresarial\Repositories\CTE\RelevantInformation;

class Cte extends Model
{
    protected $guarded = [
        'id'
    ];

    /**
     * Relation with the F22 form
     * @return [type] [description]
     */
    public function f22s()
    {
        return $this->hasMany('acempresarial\Models\F22');
    }

    /**
     * Relation with the F29 form
     * @return [type] [description]
     */
    public function f29s()
    {
        return $this->hasMany('acempresarial\Models\F29');
    }

      /**
     * Relation with the LegalRepresentatives model
     * @return [type] [description]
     */
    public function legalRepresentatives()
    {
        return $this->hasMany('acempresarial\Models\LegalRepresentative');
    }

    /**
     * Relation with the Partner model
     * @return [type] [description]
     */
    public function partners()
    {
        return $this->hasMany('acempresarial\Models\Partner');
    }

    /**
     * Relation with the Report model
     * @return [type] [description]
     */
    public function reports()
    {
        return $this->hasMany('acempresarial\Models\Report');
    }

     /**
     * Relation with the Economic Activities form
     * @return [type] [description]
     */
    public function economicActivities()
    {
        return $this->belongsToMany('acempresarial\Models\EconomicActivity')->withTimestamps();
    }

    /**
     * Relation with company.
     * @return [type] [description]
     */
    public function company()
    {
        return $this->belongsTo('acempresarial\Models\Company');
    }

    /**
     * Retreives all information relevant to the CTE
     */
    public function relevantInformation()
    {
        return RelevantInformation::get($this);
    }

     /**
     * Get all of the Economic sectors
     * of the CTE.
     */
    public function economicActivitiesArray()
    {
        $sectors = [];
        foreach ($this->economicActivities as $key => $activity) {
            $sectors[$activity->id]=$activity->name;     
        }
        return $sectors;
    }


}

app/Models/F22.php
<?php

namespace acempresarial\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class F22 extends Model
{
     protected $guarded = [
        'id'
    ];

     public function cte()
    {
        return $this->belongsTo('acempresarial\Models\Cte');
    }

     /**
	 * The string attribute that should be cast to custom carbon date.
	 *
	 * @var array
	 */

	public function getTaxYearAttribute($value)
	{
	    return Carbon::createFromFormat('Y-m-d H:i:s', $value);
	}
}

app/Http/Controllers/CTEsController.php
<?php

namespace acempresarial\Http\Controllers;

use Illuminate\Http\Request;
use acempresarial\Http\Requests;
use acempresarial\Repositories\CTE\CteUploaderRepository;
use acempresarial\Repositories\CTE\CteSaverRepository;
use acempresarial\Models\Cte;
use Auth;
use acempresarial\Repositories\CTE\CteEvaluationRepository;
use acempresarial\Repositories\CTE\CteValidators\CteArrayValidator;
use DB;


class CTEsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {    	
        $ctes = Cte::where('user_id','=',Auth::user()->id)
                ->orderBy('created_at','DESC')->get();

        $f29_count = 0;
        $f22_count = 0;
        foreach ($ctes as $cte) {
           
           $f29_count = $f29_count + $cte->f29s->count();
           $f22_count = $f22_count + $cte->f22s->count();
        }    

        return view('cte.index', compact('ctes','f29_count','f22_count'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {       
        $cte = Cte::findOrFail($id);
        return view('cte.show',compact('cte'));
    }

    /**
     * PDF upload for the CTE
     * @param  Request $request PDF
     * @param  int  $user_id User's ID
     * @return json           success/fail
     */
    public function upload(Request $request, $user_id,
    	CteUploaderRepository $uploadManager, CteSaverRepository $cte, CteArrayValidator $validator)
    {     
        $file = $request->file('file'); 
            
        $CTE = $uploadManager->upload($file,"uploads/ctes/$user_id/");

 
       // $validator->validate($CTE);

        $CTE = $cte->store($CTE);
     
        return 'Done';
    }

    /**
     * Shows the page where whe can Upload the
     * CTE's PDF
     * @return view
     */
    public function uploader()
    {
    	return view('cte.upload');
    }
    /**
     * Shows the Wizard to prepare the Report
     * @param [type] $id [description]
     */
    public function EconomicActivitiesWizard($id)
    {   
        $cte = CTE::findOrFail($id);
        return view('cte.wizard',compact('cte'));
    }
}

resources/views/cte/show/_f22.blade.php
<div class="tab-pane" id="tab_3">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-solid">
				<div class="box-header with-border">
					<h3 class="box-title">Detalle de Formularios 22 presentados</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					@forelse($cte->relevantInformation()->f22s as $f22) 
					<div class="box-group" id="F22accordion">
						<!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
						<div class="panel box box-primary">
							<a data-toggle="collapse" data-parent="#F22accordion" href="#F22collapse{{$f22->id}}" aria-expanded="false" class="collapsed">
								<div class="box-header with-border">
									<h4 class="box-title">
									
									Formulario Año {{$f22->tax_year->format('Y')}}
									
									</h4>
								</div>
							</a>
							<div id="F22collapse{{$f22->id}}" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
								
								<div class="box-body no-padding">
									<table class="table table-striped">
										<thead>

											<th class="col-md-3"></th>
											<th class="col-md-3"></th>
											<th class="col-md-3"></th>
											<th class="col-md-3"></th>

										</thead>
										<tbody>
											<input type="hidden" name="f22[id][]" value="{{$f22->id}}">
											
											@foreach(array_chunk($f22->toArray(),4,true) as $chunckedF22)
											<tr>
												@foreach($chunckedF22 as $field => $value)
												<td style="vertical-align: middle !important;" >
													<label>{{trans("f22.$field")}}</label>
													<input type="text" class="form-control"
													name="F22[$field][]" placeholder="RUT" value="{{$value}}">
													
												</td>
												
												@endforeach
											</tr>
											
											@endforeach
											
											
										</tbody></table>
									</div>
								</div>
								
							</div>
							
						</div>
						@empty
						@endforelse
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			
		</div>
		
	</div>

resources/views/cte/show/_f29.blade.php
<div class="tab-pane" id="tab_2">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-solid">
				<div class="box-header with-border">
					<h3 class="box-title">Detalle de Formularios 29 presentados</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					@forelse($cte->relevantInformation()->f29s as $f29)
					<div class="box-group" id="accordion">
						<!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
						<div class="panel box box-primary">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapse{{$f29->id}}" aria-expanded="false" class="collapsed">
								<div class="box-header with-border">
									<h4 class="box-title">
									

									Formulario Mes {{$f29->C15->format('m')}} de {{$f29->C15->format('Y')}}

									
									</h4>
								</div>
							</a>
							<div id="collapse{{$f29->id}}" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
								
								<div class="box-body no-padding">
										
								
									<table class="table table-condensed table-striped">
										<thead>

											<tr>
												<th class="col-md-3"></th>
												<th class="col-md-3"></th>
												<th class="col-md-3"></th>
												<th class="col-md-3"></th>
											</tr>
										</thead>
										<tbody>
											
											@foreach(array_chunk($f29->toArray(),4,true) as $partialF29)
											<tr>
												@foreach($partialF29 as $key => $value)
												<td>
													<div class="text-center">
														<label>{{trans("f29.".$key)}}</label>
													</div>
												</td>
												@endforeach
											</tr>
											<tr>
												@foreach($partialF29 as $key => $value)
												<td>
													<div class="text-center">
														<input type="text" name="CTE[F29][{{$key}}]" class="form-control" placeholder="{{trans("f29.".$key)}}" value="{{$value}}">
													</div>
												</td>
												@endforeach
											</tr>
											@endforeach	

										</tbody></table>
									
									
									</div>
								</div>
								
							</div>
							
						</div>
						@empty
						@endforelse
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			
		</div>
		
	</div>

resources/views/cte/show/_primary.blade.php
<div class="tab-pane active" id="tab_1">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Información General de la Empresa</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">
      <table class="table table-striped">
        <thead>         
          <th class="col-md-4"></th>
          <th class="col-md-4"></th>
          <th class="col-md-4"></th>
        </thead>
        <tbody>
        <tr>
          
          <td style="vertical-align: middle !important;" >
            <label>RUT</label>
            <input type="text" class="form-control" placeholder="RUT" value="{{$cte->company->rut}}">
          </td>
         
          <td style="vertical-align: middle !important;">            
            <label>Nombre</label>
             <input type="text" class="form-control" placeholder="Nombre" name="F22[name][]" value="{{$cte->company->name}}">
          </td>          
        </tr>
         <tr>
          
          <td style="vertical-align: middle !important;">{{$cte->company->address}}</td>
          <td style="vertical-align: middle !important;"><h4>Categoría Tributaria:</h4</td>
          <td style="vertical-align: middle !important;">
          @if(isset($cte->company->tax_category))
          
          {{$cte->company->tax_category}}
          @endif
          </td>          
        </tr>
           
          <td style="vertical-align: middle !important;" >{{$cte->evaluation}}</td>
          <td style="vertical-align: middle !important;"><h4>Nombre:</h4></td>
          <td style="vertical-align: middle !important;">{{$cte->company->name}}</td>
        <tr>
        </tr>
      </tbody></table>
    </div>
    <!-- /.box-body -->
  </div>
</div>